### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by Lmmb74** [Simonsator/Party-Toggle#1]
https://github.com/Simonsator/Party-Toggle/blob/36d76c8a1548d7c8d26be83af9bc2f2d52b368d3/src/main/resources/plugin.yml#L6

I guess there is not really much to say XD.

**Comment by Simonsator** [comment]
Seems like a copy and paste error. Fixed with https://github.com/Simonsator/Party-Toggle/commit/5db1c2fc944b4ef4fc397edec3ff6afead2578c6
